version: "3.8"

services:
  devtasker-api:
    container_name: devtasker-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:3000"
      - "9229:9229"
    env_file:
      - .env.dev
    depends_on:
      - postgres
    command: sh -c "npm run debug"

  postgres:
    image: postgres:15
    container_name: devtasker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devtasker
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devtasker
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres-data:
